<script setup lang="ts">
import { onMounted,ref,watch } from 'vue'
import { api,ui,run } from './api'
const code=ref(''),status=ref<any>(null),rules=ref<any>(null),draft=ref<Record<string,string>>({}),checked=ref<any>(null),confirmed=ref(false),saving=ref(false)
const names:Record<string,string>={abnormality:'实验现象',band_pattern:'条带特征',cause:'异常原因',priority:'优先级',positive_control:'阳性对照',negative_control:'阴性对照',template_condition:'模板状态',annealing_temp_condition:'退火温度状态',text_hint:'事实线索',required_fields:'必需证据字段',base_score:'基础分',evidence_text:'证据描述',suggestion:'建议措施',enabled:'启用（1）或停用（0）'}
async function load(){await run(async()=>{status.value=await api('/dev/status');rules.value=await api('/dev/rules');if(!Object.keys(draft.value).length){for(const column of rules.value.columns.filter((c:string)=>c!=='rule_id'))draft.value[column]=({priority:'80',base_score:'70',enabled:'0',required_fields:'',abnormality:'无条带',cause:'',evidence_text:'',suggestion:''} as any)[column]??'any'}},'')}
async function login(){await run(async()=>{await api('/session',{role:'dev',code:code.value});code.value='';ui.role='dev';ui.caseIds=[];await load()},'已进入开发调试')}
async function logout(){await run(async()=>{await api('/logout',{},'POST');ui.role='';status.value=null;rules.value=null;draft.value={};checked.value=null},'已退出开发调试')}
async function check(){checked.value=null;confirmed.value=false;await run(async()=>{checked.value=await api('/dev/rules/check',{rule:draft.value,version:rules.value.version})},'规则检查完成，请复核后保存')}
async function save(){if(saving.value||!checked.value||!confirmed.value)return;saving.value=true;try{await run(async()=>{const result=await api('/dev/rules',{rule:draft.value,version:checked.value.version,confirmed:confirmed.value});draft.value={};checked.value=null;confirmed.value=false;await load();return result},'新规则已保存，原规则文件已备份')}finally{saving.value=false}}
watch(draft,()=>{checked.value=null;confirmed.value=false},{deep:true})
watch(()=>ui.role,role=>{if(role==='dev')load();else{status.value=null;rules.value=null}})
onMounted(()=>{if(ui.role==='dev')load()})
</script>
<template>
<div class="page-title"><div><p class="eyebrow">系统维护</p><h1>开发调试控制台</h1><p class="muted">系统自检、模型调用状态与规则库维护。</p></div><button v-if="ui.role==='dev'" class="secondary" @click="logout">退出开发调试</button></div>
<section v-if="ui.role!=='dev'" class="panel narrow"><h2>开发访问验证</h2><p class="muted">请输入独立的开发访问码。进入后将切换当前浏览器身份。</p><form @submit.prevent="login"><label>开发访问码<input type="password" v-model="code" required maxlength="200" autocomplete="off"></label><button>进入开发调试</button></form><p class="small muted">尚未设置时，在启动器“配置”中填写调试访问码，或配置 DEV_ACCESS_CODE 后重启服务。</p></section>
<template v-else-if="status&&rules">
<div class="section-head"><h2>系统自检</h2><button class="secondary" @click="load">刷新自检</button></div>
<div class="two-col"><section class="panel" v-for="item in status.checks" :key="item.name"><h3>{{item.name}} · {{item.ok?'正常':'需检查'}}</h3><p>{{item.detail}}</p></section></div>
<section class="panel"><h2>模型接口配置</h2><dl class="entry-fields"><dt>接口地址</dt><dd>{{status.base_url}}</dd><dt>模型标识</dt><dd>{{status.model}}</dd><dt>凭据状态</dt><dd>{{status.key_configured?'已配置':'未配置'}}</dd><dt>图像辅助观察</dt><dd>{{status.vision_enabled?'已开启':'已关闭'}}；主动确认后才请求</dd><dt>超时与重试</dt><dd>文字 {{status.text_timeout}} 秒；图片 {{status.vision_timeout}} 秒；重试 0 次</dd></dl><p class="small muted">此页不显示密钥；刷新自检不会请求模型。</p><h3>最近图像调用</h3><div v-if="status.calls.length" class="table-scroll"><table><thead><tr><th>观察版本</th><th>案例编号</th><th>时间</th><th>状态</th><th>模型</th><th>Token</th></tr></thead><tbody><tr v-for="call in status.calls" :key="call.id"><td>{{call.id}}</td><td>{{call.record_id}}</td><td>{{call.created_at}}</td><td>{{call.status==='success'?'已保存候选':'请求未完成'}}</td><td>{{call.model_requested}}</td><td>{{call.total_tokens??'未知'}}</td></tr></tbody></table></div><p v-else class="muted">暂无保存的图像调用记录。</p><p class="small muted">未返回 Token 用量不代表未计费，实际费用请以 DeepSeek 账单为准。</p><p class="small muted">人工整理事实时不会调用文本抽取接口，因此本页不显示文本抽取记录。</p></section>
<section class="panel"><div class="section-head"><h2>规则库查看与校验</h2><button class="secondary" @click="load">检查规则库</button></div><p :class="rules.ok?'notice':'notification error'">{{rules.ok?'规则库检查通过':rules.issues.join('；')}}</p><p class="small muted preserve">规则版本：{{rules.version}}</p><div class="table-scroll"><table><thead><tr><th v-for="column in rules.columns" :key="column">{{names[column]??column}}</th></tr></thead><tbody><tr v-for="row in rules.rows" :key="row.rule_id"><td v-for="column in rules.columns" :key="column">{{row[column]}}</td></tr></tbody></table></div></section>
<section class="panel"><h2>规则库在线编辑</h2><p class="muted">新增规则需先检查并确认。默认停用；启用后会影响后续新诊断，历史记录保留原结果。</p><details><summary>添加新规则</summary><form @submit.prevent="check"><div class="fields"><label v-for="column in rules.columns.filter((c:string)=>c!=='rule_id')" :key="column">{{names[column]??column}}（{{column}}）<textarea v-if="['evidence_text','suggestion'].includes(column)" v-model="draft[column]" maxlength="2000" rows="3" required/><input v-else v-model="draft[column]" maxlength="2000" :required="['abnormality','cause','priority','base_score','enabled'].includes(column)"></label></div><button>检查新增规则</button></form><div v-if="checked" class="notice"><p>拟新增编号：{{checked.rule.rule_id}}</p><p v-for="warning in checked.warnings" :key="warning">{{warning}}</p><label class="check"><input type="checkbox" v-model="confirmed">我已核对匹配条件、证据与分数，确认保存并备份原文件</label><button :disabled="!confirmed||saving" @click="save">{{saving?'保存中…':'确认添加规则'}}</button></div></details></section>
</template>
</template>
