<script setup lang="ts">
import { computed,reactive,ref,watch } from 'vue'
import { api,run,ui,parse } from './api'
import Lanes from './Lanes.vue'
const props=defineProps<{record:any,teacher?:boolean}>();const emit=defineEmits<{refresh:[]}>()
const count=ref(1),mapping=ref<any[]>([{lane_id:1,role:'身份未确认'}]),settings=reactive({rotation:0,left:0,top:0,right:100,bottom:100}),preview=ref<any>(null),consent=ref(false),busy=ref(false),lanes=ref<any[]>([]),force=ref(false)
const latest=computed(()=>props.record.gel?.runs.find((r:any)=>r.status==='success'))
watch(count,n=>{mapping.value=Array.from({length:n},(_,i)=>({lane_id:i+1,role:mapping.value[i]?.role??'身份未确认'}))})
watch([mapping,settings],()=>{preview.value=null;consent.value=false},{deep:true})
watch(latest,run=>{if(run){const checks=props.record.gel.checks.find((c:any)=>c.run_id===run.id&&c.actor===(props.teacher?'teacher':'student'));lanes.value=checks?JSON.parse(JSON.stringify(checks.entries)):run.observations.lanes.map((l:any)=>({...l,state:'未核对',note:''}))}},{immediate:true})
async function prepare(){await run(async()=>{preview.value=await api(`/cases/${props.record.id}/gel/preview`,{mapping:mapping.value,settings})},'已生成发送区域预览，请核对后再确认')}
async function observe(){busy.value=true;await run(async()=>{const response=await api(`/cases/${props.record.id}/gel/observe`,{mapping:mapping.value,settings,context_key:preview.value.context_key,consent:consent.value,force:force.value});if(response.status!=='success')throw new Error(response.error);emit('refresh')},'辅助观察已保存，请逐项对照原图核对');busy.value=false}
async function check(){await run(async()=>{const student=props.record.gel.checks.find((c:any)=>c.run_id===latest.value.id&&c.actor==='student');await api(`/cases/${props.record.id}/gel/check`,{run_id:latest.value.id,context_key:latest.value.context_key,entries:lanes.value,source_student_check_id:student?.id??null});emit('refresh')},props.teacher?'教师图像复核已保存':'学生图像核对已保存')}
</script>
<template><section v-if="record.has_image" class="panel"><h2>电泳图与辅助观察</h2><p class="notice">图像 AI 只描述可见现象。原始候选、学生核对和教师图像复核独立保存，不直接参与原因排序或成绩。</p><img :src="`/api/v1/cases/${record.id}/image`" class="gel-image" alt="案例原始电泳图">
<details v-if="!teacher"><summary>设置发送区域与匿名泳道身份</summary><div class="fields"><label>泳道数量<input type="number" v-model.number="count" min="1" max="30"></label><label>顺时针旋转<select v-model.number="settings.rotation"><option :value="0">不旋转</option><option :value="90">90°</option><option :value="180">180°</option><option :value="270">270°</option></select></label><label v-for="key in (['left','top','right','bottom'] as const)" :key="key">{{({left:'左边界',top:'上边界',right:'右边界',bottom:'下边界'})[key]}}（%）<input type="number" v-model.number="settings[key]" min="0" max="100"></label></div><div class="fields"><label v-for="m in mapping" :key="m.lane_id">泳道 {{m.lane_id}}<select v-model="m.role"><option v-for="v in ui.config.roles" :key="v">{{v}}</option></select></label></div><button class="secondary" @click="prepare">预览发送区域</button><template v-if="preview"><img :src="preview.preview" class="gel-image" alt="准备发送的处理副本"><label class="check"><input type="checkbox" v-model="consent">我已核对区域与泳道身份，已去除图片中可见的身份信息，同意将处理副本发送给 DeepSeek。</label><label v-if="latest" class="check"><input type="checkbox" v-model="force">重新请求相同设置的图像（产生新调用）</label><button :disabled="!consent||busy||!ui.config.vision_available" @click="observe">{{busy?'正在辅助观察…':'请求 AI 辅助观察'}}</button><p v-if="!ui.config.vision_available" class="muted">未配置接口或图像功能已关闭，可继续人工复盘。</p></template></details>
<template v-if="latest"><h3>原始候选 · 版本 #{{latest.id}}</h3><p>{{latest.observations.quality}} · {{latest.observations.quality_issues.join('、')||'未提出质量问题'}}</p><div class="table-scroll"><table><thead><tr><th>泳道</th><th>数量</th><th>形态</th><th>位置</th><th>亮度</th></tr></thead><tbody><tr v-for="l in latest.observations.lanes" :key="l.lane_id"><td>{{l.lane_id}}</td><td>{{l.band_count??'未知'}}</td><td>{{l.pattern}}</td><td>{{l.position}}</td><td>{{l.brightness}}</td></tr></tbody></table></div><h3>{{teacher?'教师对照原图复核':'学生对照原图核对'}}</h3><p class="muted small">更改观察时请选择“已修正”；看不清时请选择“无法确认”。</p><Lanes :lanes="lanes" checking/><button @click="check">保存人工核对</button></template><details v-if="record.gel?.checks.length"><summary>历次图像核对记录</summary><div v-for="c in record.gel.checks" :key="c.id"><h4>{{c.actor==='teacher'?'教师':'学生'}}核对 #{{c.id}} · 观察 #{{c.run_id}}</h4><p v-for="l in c.entries" :key="l.lane_id">泳道 {{l.lane_id}}：{{l.state}}，条带数 {{l.band_count??'未知'}} · {{l.note}}</p></div></details></section></template>
