<script setup lang="ts">
import { ref,watch } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { api,ui,run } from './api'
const route=useRoute(),router=useRouter(),task=ref<any>(null),taskCode=ref(sessionStorage.getItem('bio_task')??''),queryCode=ref('')
watch(()=>route.params.code,async(code)=>{if(code)await run(async()=>{task.value=await api('/tasks/'+encodeURIComponent(String(code)));taskCode.value=task.value.code;sessionStorage.setItem('bio_task',task.value.code)},'')},{immediate:true})
async function join(){if(taskCode.value)await router.push('/tasks/'+encodeURIComponent(taskCode.value.trim()))}
async function recover(){await run(async()=>{const state=await api('/session',{code:queryCode.value,role:'student'});queryCode.value='';ui.role='student';ui.caseIds=[state.case_id];router.push('/cases/'+state.case_id)},'已找回实验案例')}
</script>
<template><section class="hero"><p class="eyebrow">探索关联 · 记录证据 · 修订解释</p><h1>连接生物知识学习与实验分析</h1><p class="lead">从理解生物功能网络，到分析实验现象，在原理与证据之间建立联系。</p></section>
<div class="module-grid"><RouterLink to="/knowledge" class="module-card"><span class="module-index">01 / 知识探索</span><h2>{{ui.config.brand?.modules?.knowledge.name??'生物功能图谱'}}</h2><p>{{ui.config.brand?.modules?.knowledge.description??'探索基因、蛋白与代谢物的通路关联'}}</p><b>进入生物功能图谱 →</b></RouterLink><RouterLink to="/experiment" class="module-card dark"><span class="module-index">02 / 异常分析</span><h2>{{ui.config.brand?.modules?.experiment.name??'电泳异常分析'}}</h2><p>{{ui.config.brand?.modules?.experiment.description??'结合实验记录与对照结果分析电泳异常，通过教师反馈和复测验证改进判断'}}</p><b>进入电泳异常分析 →</b></RouterLink></div>
<div class="two-col"><section class="panel"><p class="eyebrow">课堂任务</p><h2>我的课堂任务</h2><p class="muted">输入教师提供的任务码，查看实验要求与相关知识。</p><form @submit.prevent="join" class="inline-form"><label class="grow">任务码<input v-model="taskCode" required maxlength="30" placeholder="请输入任务码"></label><button>查看任务</button></form><div v-if="task" class="task-detail"><h3>{{task.title}}</h3><p class="preserve">{{task.instructions}}</p><p class="muted">版本 {{task.version}} · {{task.status}} · {{task.due_at||'未设置截止时间'}}</p><p>{{task.knowledge_note}}</p><div class="chips"><RouterLink v-for="entry in task.knowledge.items" :key="entry.id" :to="{path:'/knowledge/'+entry.id,query:{task:task.code}}">{{entry.name}} ↗</RouterLink></div><RouterLink class="button" :to="{path:'/experiment',query:{task:task.code}}">记录本次实验</RouterLink></div></section>
<section class="panel"><p class="eyebrow">学习记录</p><h2>找回实验案例</h2><p class="muted">输入保存的私有查询码，可在其他设备上找回案例和后续反馈。</p><form @submit.prevent="recover" class="inline-form recover-form"><label class="grow">私有查询码<input type="password" v-model="queryCode" required autocomplete="off"></label><button>找回案例</button></form><div v-if="ui.caseIds.length" class="chips"><RouterLink v-for="id in ui.caseIds" :key="id" :to="'/cases/'+id">案例 #{{id}}</RouterLink></div></section></div>
</template>
