<script setup lang="ts">
import { ref,watch,onMounted } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { api,run,parse,download,notify,ui } from './api'
import Network from './Network.vue'
const route=useRoute(),router=useRouter(),q=ref(''),kind=ref(''),offset=ref(0),results=ref<any>({items:[],total:0}),entry=ref<any>(null),favorites=ref<any[]>(parse(localStorage.getItem('bio_favorites_v1'),[])),missing=ref<string[]>([]),showFav=ref(false)
async function search(reset=true){if(reset)offset.value=0;await run(async()=>results.value=await api(`/knowledge?q=${encodeURIComponent(q.value)}&kind=${kind.value}&offset=${offset.value}`),'')}
function go(id:string){router.push({path:'/knowledge/'+id,query:route.query})}
watch(()=>route.params.id,async(id)=>{entry.value=null;if(id)await run(async()=>entry.value=await api('/knowledge/'+id),'')},{immediate:true})
function saveFavorites(){localStorage.setItem('bio_favorites_v1',JSON.stringify(favorites.value))}
function toggle(){if(!entry.value)return;const i=favorites.value.findIndex(e=>e.id===entry.value.id);if(i<0)favorites.value.push({id:entry.value.id,name:entry.value.name,kind:entry.value.kind,version:entry.value.version});else favorites.value.splice(i,1);saveFavorites()}
async function importFile(e:Event){const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;await run(async()=>{if(file.size>2000000)throw new Error('收藏文件过大。');const data=JSON.parse(await file.text());const items=Array.isArray(data)?data:data.items;if(!Array.isArray(items))throw new Error('收藏格式无效。');const ids=items.map((x:any)=>typeof x==='string'?x:(x.id??x.k));const result=await api('/knowledge/resolve',{ids});favorites.value=[...new Map([...favorites.value,...result.items].map(x=>[x.id,x])).values()];missing.value=result.missing;saveFavorites()},'收藏已导入；无法对应的项目另行列出')}
onMounted(()=>{search();if(favorites.value.length)run(async()=>{const result=await api('/knowledge/resolve',{ids:favorites.value.map(x=>x.id)});missing.value=result.missing},'')})
</script>
<template><div class="page-title"><div><p class="eyebrow">知识探索</p><h1>{{ui.config.brand?.modules?.knowledge.name??'生物功能图谱'}}</h1><p class="muted">{{ui.config.brand?.modules?.knowledge.description??'探索基因、蛋白与代谢物的通路关联'}}</p></div><RouterLink v-if="route.query.task" :to="'/tasks/'+route.query.task" class="button secondary">返回课堂任务</RouterLink><RouterLink v-else to="/experiment" class="button secondary">返回实验记录</RouterLink></div>
<form @submit.prevent="search()" class="search-panel"><input aria-label="搜索生物词条" v-model="q" placeholder="中文名、英文名、别名、基因符号或通路" maxlength="200"><select v-model="kind" aria-label="词条类型" @change="search()"><option value="">全部类型</option><option value="met">代谢物</option><option value="prot">蛋白／酶</option><option value="gene">基因</option><option value="pw">通路</option></select><button>查询</button><button type="button" class="secondary" @click="showFav=!showFav">收藏 {{favorites.length}}</button></form>
<section v-if="showFav" class="panel"><div class="section-head"><h2>本机收藏</h2><button class="secondary" @click="download('生物功能图谱收藏.json',{version:1,items:favorites})">导出收藏</button></div><label>导入收藏文件<input type="file" accept=".json" @change="importFile"></label><p class="muted small">收藏保存在当前浏览器，不自动同步到其他设备。导入旧版导出的数组编号时，按随包保存的旧版映射处理。</p><div class="chips"><button v-for="f in favorites" :key="f.id" class="secondary" @click="go(f.id)">{{f.name}}</button></div><p v-if="missing.length" class="notice">以下词条目前无法对应，请重新查询：{{missing.join('、')}}</p></section>
<div class="knowledge-layout"><aside class="panel search-results"><div class="section-head"><h2>查询结果</h2><span class="muted">{{results.total}} 项</span></div><button v-for="item in results.items" :key="item.id" :class="['result-row',{active:entry?.id===item.id}]" @click="go(item.id)"><span :class="['type-dot',item.kind]"></span><span><b>{{item.name}}</b><small>{{item.english||({met:'代谢物',prot:'蛋白／酶',gene:'基因',pw:'通路'} as any)[item.kind]}}</small></span><span>›</span></button><p v-if="!results.total" class="muted">未收录匹配词条，可尝试其他名称或别名。</p><div class="section-head"><button class="quiet" :disabled="offset===0" @click="offset=Math.max(0,offset-30);search(false)">上一页</button><button class="quiet" :disabled="offset+30>=results.total" @click="offset+=30;search(false)">下一页</button></div></aside>
<article v-if="entry" class="panel entry"><div class="section-head"><div><p class="eyebrow">{{({met:'代谢物',prot:'蛋白／酶',gene:'基因',pw:'通路'} as any)[entry.kind]}}</p><h2>{{entry.name}}</h2><p class="muted">{{entry.english}}</p></div><button class="secondary" @click="toggle">{{favorites.some(x=>x.id===entry.id)?'★ 已收藏':'☆ 收藏'}}</button></div><p class="notice">{{entry.notice}}</p><Network v-if="entry.kind!=='pw'" :entry="entry" @select="go"/><dl class="entry-fields"><template v-for="(value,key) in entry.fields" :key="key"><dt>{{key}}</dt><dd>{{value}}</dd></template><dt>物种</dt><dd>{{entry.species}}</dd><dt>整理来源</dt><dd>{{entry.source}}</dd></dl><h3 v-if="entry.pathways.length">所属通路</h3><div class="chips"><button v-for="p in entry.pathways" :key="p.id" @click="go(p.id)" class="secondary">{{p.name}}</button></div><h3>{{entry.kind==='pw'?'通路内收录词条':'完整关联列表'}}</h3><div class="relation-list"><button v-for="(r,i) in entry.relations" :key="i" class="relation-row" @click="go(r.to)"><b>{{r.target.name}}</b><span>{{r.basis}}</span><em>{{r.status}}</em></button><button v-for="m in entry.members" :key="m.id" class="relation-row" @click="go(m.id)"><b>{{m.name}}</b><span>同通路收录</span></button><p v-if="!entry.relations.length&&!entry.members.length" class="muted">尚未收录关联记录。</p></div><p class="muted small">数据版本：{{entry.version}}</p></article>
<section v-else class="panel empty-state"><span class="large-symbol">⌘</span><h2>选择一个词条，展开它的关联</h2><p>可从“丙酮酸”“己糖激酶”“HK1”或“糖酵解”开始。</p></section></div></template>
