<script setup lang="ts">
import { computed,ref } from 'vue'
const props=defineProps<{entry:any}>();defineEmits<{select:[id:string]}>()
const scale=ref(1),pan=ref({x:0,y:0}),start=ref<any>(null)
const nodes=computed(()=>{const all=[props.entry,...props.entry.relations.map((r:any)=>r.target)];const seen=new Set();return ['met','prot','gene'].flatMap((kind,layer)=>all.filter((n:any)=>n.kind===kind&&!seen.has(n.id)&&seen.add(n.id)).slice(0,7).map((n:any,i:number)=>({...n,x:85+i*130,y:65+layer*130})))})
const edges=computed(()=>props.entry.relations.filter((e:any)=>nodes.value.some((n:any)=>n.id===e.from)&&nodes.value.some((n:any)=>n.id===e.to)).map((e:any)=>({...e,a:nodes.value.find((n:any)=>n.id===e.from),b:nodes.value.find((n:any)=>n.id===e.to)})))
function begin(e:PointerEvent){if((e.target as Element).closest('.graph-node'))return;start.value={x:e.clientX,y:e.clientY,px:pan.value.x,py:pan.value.y};(e.currentTarget as Element).setPointerCapture(e.pointerId)}
function move(e:PointerEvent){if(start.value)pan.value={x:start.value.px+(e.clientX-start.value.x)/scale.value,y:start.value.py+(e.clientY-start.value.y)/scale.value}}
</script>
<template><div class="graph-toolbar"><b>关联网络</b><div><button class="quiet" @click="scale=Math.max(.5,scale-.2)" aria-label="缩小图谱">−</button><button class="quiet" @click="scale=Math.min(3,scale+.2)" aria-label="放大图谱">＋</button><button class="quiet" @click="scale=1;pan={x:0,y:0}">重置视图</button></div></div><div class="graph-window"><svg viewBox="0 0 960 400" role="img" aria-label="代谢物、蛋白和基因关联图，可拖动和缩放" @pointerdown="begin" @pointermove="move" @pointerup="start=null" @pointercancel="start=null"><g :transform="`translate(${pan.x} ${pan.y}) scale(${scale})`"><text v-for="(label,i) in ['代谢物','蛋白／酶','基因']" :key="label" x="8" :y="30+i*130" class="layer-label">{{label}}</text><line v-for="(edge,i) in edges" :key="i" :x1="edge.a.x" :y1="edge.a.y+18" :x2="edge.b.x" :y2="edge.b.y+18" :class="['edge',edge.type==='co'?'co':'']"><title>{{edge.basis}} · {{edge.status}}</title></line><g v-for="node in nodes" :key="node.id" :transform="`translate(${node.x-57} ${node.y})`" class="graph-node" role="button" :aria-label="node.name" tabindex="0" @click.stop="$emit('select',node.id)" @keydown.enter="$emit('select',node.id)"><rect width="114" height="38" rx="8" :class="node.kind" :stroke-width="node.id===entry.id?3:1"/><text x="57" y="24" text-anchor="middle">{{node.name.length>8?node.name.slice(0,7)+'…':node.name}}</text><title>{{node.name}}</title></g></g></svg></div><p class="muted small">每层最多显示 7 个关联词条，完整关系请查看下方列表。连线表示词条间的关联，实线关系也未经人工确认；虚线仅表示同通路。</p></template>
