<script setup lang="ts">
import { computed,onMounted,reactive,ref,watch } from 'vue'
import { api,ui,run,parse,labels } from './api'
import Fields from './Fields.vue'
import Experiment from './Experiment.vue'
import Evaluation from './Evaluation.vue'
const access=ref(''),tab=ref('cases'),cases=ref<any[]>([]),filter=ref(''),selected=ref<number|null>(null),independent=ref<any>(null),regular=ref(false),judgment=reactive<any>({cause:'',reason:'',evidence_level:'原因待核实'}),review=reactive<any>({cause:'',note:'',evidence_level:'原因待核实',verification_feedback:'',version:0}),evaluation=reactive<any>({stage:'initial',rubric:{},note:''}),tasks=ref<any[]>([]),schemes=ref<any[]>([]),knowledgeQuery=ref(''),found=ref<any[]>([]),chosen=ref<any[]>([]),task=reactive<any>({title:'',instructions:'',transfer_prompt:'',due_at:'',knowledge_note:'',scheme_id:null,parent_task_id:null}),scheme=reactive<any>({name:'',source:'',payload:{template_type:'待确认'},expected_version:0}),issues=ref<any>(null),issueTask=ref<number|null>(null)
const visibleCases=computed(()=>cases.value.filter(c=>`${c.id} ${c.class_name} ${c.group_code} ${c.course_name}`.includes(filter.value)))
async function load(){await run(async()=>{cases.value=await api('/teacher/cases');tasks.value=await api('/teacher/tasks');schemes.value=await api('/schemes');for(const d of ui.config.dimensions??[])evaluation.rubric[d]=null},'')}
async function login(){await run(async()=>{await api('/session',{role:'teacher',code:access.value});access.value='';ui.role='teacher';await load()},'已进入教师工作区')}
async function logout(){await run(async()=>{await api('/logout',{},'POST');ui.role='';ui.caseIds=[];selected.value=null},'已退出教师身份')}
async function select(rid:number){selected.value=rid;regular.value=false;independent.value=null;await run(async()=>{independent.value=await api(`/teacher/cases/${rid}/independent`);Object.assign(judgment,{cause:'',reason:'',evidence_level:'原因待核实'})},'')}
async function showRegular(){await run(async()=>{const record=await api('/cases/'+selected.value);Object.assign(review,{cause:record.teacher_final_cause??'',note:record.teacher_note??'',evidence_level:record.teacher_evidence_level??'原因待核实',verification_feedback:record.verification_feedback??'',version:record.teacher_review_version??0});regular.value=true},'')}
async function saveReview(){await run(async()=>{await api(`/teacher/cases/${selected.value}/review`,review);await showRegular()},'教师反馈已保存，学生需针对当前反馈版本修订')}
async function saveTask(){await run(async()=>{await api('/teacher/tasks',{...task,knowledge_ids:chosen.value.map(e=>e.id)});await load()},'新任务版本已发布，题目、方案与关联词条已冻结')}
function reviseTask(t:any){Object.assign(task,{title:t.title,instructions:t.instructions,transfer_prompt:t.transfer_prompt,due_at:'',knowledge_note:t.knowledge_note,parent_task_id:t.id,scheme_id:null});chosen.value=t.knowledge.items.map((e:any)=>({...e}));window.scrollTo(0,0)}
async function search(){await run(async()=>found.value=(await api('/knowledge?q='+encodeURIComponent(knowledgeQuery.value))).items,'')}
function add(e:any){if(!chosen.value.some(i=>i.id===e.id)&&chosen.value.length<30)chosen.value.push(e)}
function usePreset(p:any){Object.assign(scheme,{name:p.name,source:p.source,payload:{...p},expected_version:0})}
function useScheme(s:any){Object.assign(scheme,{name:s.name,source:s.source,payload:parse(s.payload_json),expected_version:s.version})}
async function loadIssues(){await run(async()=>issues.value=await api('/teacher/issues'+(issueTask.value?'?task_id='+issueTask.value:'')),'')}
watch(()=>ui.role,role=>{if(role==='teacher')load()},{immediate:true})
</script>
<template><div class="page-title"><div><p class="eyebrow">课堂管理与反馈</p><h1>教师工作区</h1><p class="muted">发布任务、独立复核、反馈修订与过程评价。</p></div><button v-if="ui.role==='teacher'" class="secondary" @click="logout">退出教师身份</button></div><form v-if="ui.role!=='teacher'" class="panel narrow" @submit.prevent="login"><h2>教师访问验证</h2><label>教师访问码<input type="password" v-model="access" required autocomplete="off"></label><button>验证并进入</button></form>
<template v-else><div class="tabs"><button v-for="(name,id) in {cases:'案例复核',tasks:'课堂任务',schemes:'课程方案',issues:'班级问题',evaluation:'图像评估'}" :key="id" :class="{active:tab===id}" @click="tab=id;if(id==='issues')loadIssues()">{{name}}</button></div>
<template v-if="tab==='cases'"><div class="two-col teacher-case-layout"><section class="panel"><h2>课堂案例</h2><label>按课程、班级、组号或编号筛选<input v-model="filter"></label><button class="secondary" @click="load">刷新案例列表</button><button v-for="c in visibleCases" :key="c.id" class="result-row" @click="select(c.id)"><span><b>#{{c.id}} · {{c.abnormality}}</b><small>{{c.class_name||'未填班级'}} · {{c.group_code||'未填组号'}} · {{c.data_origin||'来源未标注'}}</small></span><span>›</span></button><p v-if="!visibleCases.length" class="muted">暂无符合条件的课堂案例。</p></section><section v-if="selected&&independent" class="panel"><h2>先独立判断 · 案例 #{{selected}}</h2><p class="notice">教师访问码由多人共用，系统无法区分具体教师。查看系统建议后，不能再将该案例记录为独立复核。</p><dl class="entry-fields"><template v-for="(v,k) in independent.raw" :key="k"><template v-if="!['input_json','has_image'].includes(String(k))"><dt>{{labels[k]??({abnormality:'实验现象',description:'原始记录',positive_control_normal:'阳性对照',negative_control_band:'阴性对照',id:'案例编号'} as any)[k]??k}}</dt><dd>{{v??'未知'}}</dd></template></template></dl><img v-if="independent.raw.has_image" :src="`/api/v1/cases/${selected}/image`" class="gel-image" alt="独立复核的原始电泳图"><form v-if="independent.eligible" @submit.prevent="run(async()=>{await api(`/teacher/cases/${selected}/independent`,judgment);await select(selected!)},'独立判断已保存')"><Fields :data="judgment" :fields="['cause','reason']" required/><label>证据等级<select v-model="judgment.evidence_level"><option v-for="v in ['经验复核','原始记录支持','复测验证','原因待核实']" :key="v">{{v}}</option></select></label><button>保存独立判断</button></form><p v-else-if="independent.review">已保存独立判断：{{independent.review.cause}} · {{independent.review.reason}}</p><p v-else class="muted">该案例已查看建议或已有教师反馈，不能补记独立判断。</p><button class="secondary" @click="showRegular">进入常规复核并查看建议</button></section></div>
<template v-if="selected&&regular"><section class="panel"><h2>教师复核意见</h2><p class="muted">当前版本 {{review.version}}。改变独立判断时，必须写明依据。</p><Fields :data="review" :fields="['cause','note','verification_feedback']"/><label>证据等级<select v-model="review.evidence_level"><option v-for="v in ['经验复核','原始记录支持','复测验证','原因待核实']" :key="v">{{v}}</option></select></label><button @click="saveReview">保存教师反馈</button><h3>人工过程评价</h3><label>阶段<select v-model="evaluation.stage"><option value="initial">初判</option><option value="revised">当前反馈对应修订</option><option value="transfer">新案例作答</option></select></label><div class="fields"><label v-for="dimension in ui.config.dimensions" :key="dimension">{{dimension}}<select v-model="evaluation.rubric[dimension]"><option :value="null">未评价</option><option v-for="n in [0,1,2]" :key="n" :value="n">{{n}}</option></select></label></div><label>评价备注<textarea v-model="evaluation.note"></textarea></label><button class="secondary" @click="run(()=>api(`/teacher/cases/${selected}/evaluate`,evaluation),'人工评价已保存')">保存阶段评价</button></section><Experiment :key="selected+'-'+review.version" :record-id="selected" teacher/></template></template>
<template v-if="tab==='tasks'"><form class="panel" @submit.prevent="saveTask"><h2>{{task.parent_task_id?'发布任务新版本':'发布课堂任务'}}</h2><Fields :data="task" :fields="['title','instructions','due_at','transfer_prompt','knowledge_note']"/><label>关联课程方案<select v-model="task.scheme_id"><option :value="null">不关联</option><option v-for="s in schemes" :key="s.id" :value="s.id">{{s.name}} · v{{s.version}}</option></select></label><h3>选择相关知识</h3><div class="inline-form"><input v-model="knowledgeQuery" aria-label="搜索任务相关知识" @keydown.enter.prevent="search"><button type="button" class="secondary" @click="search">搜索词条</button></div><div class="chips"><button v-for="e in found" :key="e.id" type="button" class="secondary" @click="add(e)">＋ {{e.name}}</button></div><h4>已选择 {{chosen.length}} 项</h4><div class="chips"><button v-for="e in chosen" :key="e.id" type="button" class="secondary" @click="chosen=chosen.filter(i=>i.id!==e.id)">{{e.name}} ×</button></div><button>发布本版任务</button></form><section v-for="t in tasks" :key="t.id" class="panel"><div class="section-head"><h3>{{t.title}} · v{{t.version}}</h3><b>{{t.status}}</b></div><p>任务码：<code>{{t.code}}</code></p><p class="preserve">{{t.instructions}}</p><div class="chips"><RouterLink v-for="e in t.knowledge.items" :key="e.id" :to="'/knowledge/'+e.id">{{e.name}}</RouterLink></div><div class="form-actions"><RouterLink :to="'/tasks/'+t.code" class="button secondary">查看任务页</RouterLink><button class="secondary" @click="reviseTask(t)">基于此任务发布新版本</button><button class="secondary" @click="run(async()=>{await api(`/teacher/tasks/${t.id}/status`,{active:!t.active});await load()})">{{t.active?'关闭任务':'重新开放'}}</button><a :href="`/api/v1/teacher/tasks/${t.id}/export`" class="button secondary">导出任务记录</a></div></section></template>
<template v-if="tab==='schemes'"><section class="panel"><h2>课程方案版本</h2><p class="muted">保存新版本时保留旧版；已发布任务继续使用发布时的方案。</p><div class="chips"><button v-for="p in ui.config.presets??[]" :key="p.name" class="secondary" @click="usePreset(p)">填入教师提供的讲义条件：{{p.name}}</button></div><Fields :data="scheme" :fields="['name','source']"/><Fields :data="scheme.payload" :fields="ui.config.scheme_fields??[]" :numbers="ui.config.scheme_numbers??[]" :options="{template_type:['待确认','质粒','基因组 DNA','cDNA','其他']}"/><p class="muted">基于版本 {{scheme.expected_version}}</p><button @click="run(async()=>{await api('/teacher/schemes',scheme);await load()},'课程方案新版本已保存')">保存方案新版本</button></section><section v-for="s in schemes" :key="s.id" class="panel"><h3>{{s.name}} · v{{s.version}}</h3><p>{{s.source}}</p><button class="secondary" @click="useScheme(s)">基于此版编辑</button></section></template>
<template v-if="tab==='issues'"><section class="panel"><h2>班级问题与教学建议</h2><p class="muted">仅汇总真实课堂记录；人工评价、阶段完成和复测结果分别解释，不推断学习成效。</p><label>任务范围<select v-model="issueTask" @change="loadIssues"><option :value="null">全部真实课堂</option><option v-for="t in tasks" :key="t.id" :value="t.id">{{t.title}}</option></select></label><template v-if="issues"><p>统计分母：{{issues.context.denominator}} 个课堂案例</p><div v-for="i in issues.context.issues" :key="i.code" class="issue"><h3>{{issues.actions[i.code].label}} · {{i.count}} 项</h3><p>{{issues.actions[i.code].actions.join('；')}}</p></div><button class="secondary" @click="run(async()=>{await api('/teacher/issues/suggest',{task_id:issueTask});await loadIssues()},'教学建议已保存')">根据班级问题生成教学建议</button><div v-if="issues.latest"><h3>已保存的教学建议</h3><p v-for="i in parse(issues.latest.result_json,[])" :key="i.code">{{issues.actions[i.code].label}}：{{i.action}}</p></div></template></section></template>
<Evaluation v-if="tab==='evaluation'"/>
</template></template>
